version: '2'
services: 
  dotnet-project:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        APP_ENV: Local
    ports:
      - "5111:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    external_links:
      - postgres:postgres
    entrypoint:
      - bash
      - ./run-dev.bash
    network_mode: bridge